/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Wired7475.FRC.Templates.utilities;

import Wired7475.FRC.Templates.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
