/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Wired7475.FRC.Templates.app;

import Wired7475.FRC.Templates.list.LinkedList;

import static Wired7475.FRC.Templates.utilities.StringUtils.join;
import static Wired7475.FRC.Templates.utilities.StringUtils.split;
import static Wired7475.FRC.Templates.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
